# Generated by Django 4.0.3 on 2023-06-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
